version: 2.1

orbs:
  maven: circleci/maven@2.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with-cache:
          steps:
            - run:
                name: Run tests and generate reports
                command: mvn -B clean verify
      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report
      - store_artifacts:
          path: target/extent-report
          destination: extent-report

workflows:
  build_and_test:
    jobs:
      - build
